version: '3'
services:
  gohugo-website:
  # build this local dockerfile (current working directory)
    build:
      context: .
      dockerfile: Dockerfilev2
   #   args:
   #     GO_VER: 1.16
  
    environment:
      - GO_VER=1.16
    # harbor registry container
    image: reg.wizznet.co.uk:80/wizznet/wizznet-gohugo-web
#    env_file: .env
    container_name: gohugo-website
    hostname: gohugo-website
    restart: "always"
    privileged: false
    entrypoint: ["hugo", "server", "-D", "--bind", "0.0.0.0", "-b", "10.12.12.184", "--appendPort=false"]
    ports:
      - 1313:1313
    networks:
      wizcloud_hugo:
    volumes:
      - ./site/wizzblog/config.toml:/go/src/github.com/wizzblog/config.toml


  haproxy:
    image: haproxy:latest
    restart: always
    depends_on:
      - gohugo-website
    ports:
      - 443:443
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/ssl.pem:/certs/ssl.pem:ro
      - ./haproxy/run/haproxy/:/run/haproxy/
      - ./haproxy/var/lib/haproxy:/var/lib/haproxy
    networks:
      - wizcloud_hugo

networks:
  wizcloud_hugo:
    ipam:
      driver: default

